version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.1
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: pg
    ports:
      - 5434:5432

  minio:
    image: minio/minio:RELEASE.2022-10-29T06-21-33Z
    container_name: open_budget_minio_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - open_budeget_core:/data
    hostname: open_budeget_core
    environment:
      MINIO_ROOT_USER: ${STORAGE_MINIO_USER}
      MINIO_ROOT_PASSWORD: ${STORAGE_MINIO_PASSWORD}
    command: server /data --console-address ":9001"

volumes:
  postgres_data: {}
  open_budeget_core: {}
