INSERT INTO
    district(region_id, title)
VALUES
    (1, 'Dummy District'),
    (1, 'Dummy District 2'),
    (2, 'Dummy District'),
    (2, 'Dummy District 2'),
    (3, 'Dummy District'),
    (3, 'Dummy District 2'),
    (4, 'Dummy District'),
    (4, 'Dummy District 2'),
    (5, 'Dummy District'),
    (5, 'Dummy District 2'),
    (6, 'Dummy District'),
    (6, 'Dummy District 2'),
    (7, 'Dummy District'),
    (7, 'Dummy District 2'),
    (8, 'Dummy District'),
    (8, 'Dummy District 2'),
    (9, 'Dummy District'),
    (9, 'Dummy District 2'),
    (10, 'Dummy District'),
    (10, 'Dummy District 2'),
    (11, 'Dummy District'),
    (11, 'Dummy District 2'),
    (12, 'Dummy District'),
    (12, 'Dummy District 2'),
    (13, 'Dummy District'),
    (13, 'Dummy District 2');