// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateBoard(ctx context.Context, arg CreateBoardParams) (string, error)
	CreateChronology(ctx context.Context, title string) (string, error)
	CreateDistrict(ctx context.Context, arg CreateDistrictParams) (int32, error)
	CreateDistrictBudget(ctx context.Context, arg CreateDistrictBudgetParams) error
	CreateInitiative(ctx context.Context, arg CreateInitiativeParams) (string, error)
	CreateQuarter(ctx context.Context, arg CreateQuarterParams) (int32, error)
	CreateRegion(ctx context.Context, title string) (int32, error)
	CreateStatus(ctx context.Context, title string) (int32, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (string, error)
	CreateVote(ctx context.Context, arg CreateVoteParams) error
	DeleteChronology(ctx context.Context, id string) error
	DeleteDistrictBoard(ctx context.Context, arg DeleteDistrictBoardParams) error
	DeleteDistrictByID(ctx context.Context, id int32) error
	DeleteQuearterByID(ctx context.Context, id int32) error
	DeleteRegion(ctx context.Context, id int32) error
	DeleteStatus(ctx context.Context, id int32) error
	DeleteVote(ctx context.Context, arg DeleteVoteParams) error
	GetAllBoards(ctx context.Context, arg GetAllBoardsParams) ([]Board, error)
	GetAllBoardsCount(ctx context.Context, search string) (int64, error)
	GetAllChronology(ctx context.Context, arg GetAllChronologyParams) ([]Chronology, error)
	GetAllDistrictBudget(ctx context.Context, arg GetAllDistrictBudgetParams) ([]DistrictBudget, error)
	GetAllDistricts(ctx context.Context, arg GetAllDistrictsParams) ([]District, error)
	GetAllDistrictsCount(ctx context.Context, arg GetAllDistrictsCountParams) (int64, error)
	GetAllIniativesCount(ctx context.Context, arg GetAllIniativesCountParams) (int64, error)
	GetAllInitiatives(ctx context.Context, arg GetAllInitiativesParams) ([]Initiative, error)
	GetAllQuarters(ctx context.Context, arg GetAllQuartersParams) ([]Quarter, error)
	GetAllQuartersCount(ctx context.Context, arg GetAllQuartersCountParams) (int64, error)
	GetAllRegions(ctx context.Context, arg GetAllRegionsParams) ([]Region, error)
	GetAllRegionsCount(ctx context.Context, search string) (int64, error)
	GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]User, error)
	GetAllUsersCount(ctx context.Context, arg GetAllUsersCountParams) (int64, error)
	GetAllVotes(ctx context.Context, arg GetAllVotesParams) ([]Vote, error)
	GetBoardByID(ctx context.Context, id string) (Board, error)
	GetDistrictByID(ctx context.Context, id int32) (District, error)
	GetDistrictByRegionID(ctx context.Context, regionID int32) ([]District, error)
	GetInitiativeByID(ctx context.Context, id string) (Initiative, error)
	GetQuarterByDistrictID(ctx context.Context, districtID int32) ([]Quarter, error)
	GetQuarterByID(ctx context.Context, id int32) (Quarter, error)
	GetRegionByID(ctx context.Context, id int32) (Region, error)
	GetSingleUserByID(ctx context.Context, id string) (User, error)
	GetStatus(ctx context.Context, id int32) (Status, error)
	HardDeleteBoard(ctx context.Context, id string) error
	HardDeleteUser(ctx context.Context, id string) error
	SoftDeleteBoard(ctx context.Context, arg SoftDeleteBoardParams) error
	SoftDeleteInitiative(ctx context.Context, arg SoftDeleteInitiativeParams) error
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error
	UpdateBoard(ctx context.Context, arg UpdateBoardParams) error
	UpdateChronology(ctx context.Context, arg UpdateChronologyParams) error
	UpdateDistrict(ctx context.Context, arg UpdateDistrictParams) error
	UpdateDistrictBudget(ctx context.Context, arg UpdateDistrictBudgetParams) error
	UpdateInitiativeByID(ctx context.Context, arg UpdateInitiativeByIDParams) error
	UpdateQuarter(ctx context.Context, arg UpdateQuarterParams) error
	UpdateRegion(ctx context.Context, arg UpdateRegionParams) error
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
