project:
  name: &projectName Open Budget Core
  version: 1.0.0
  time_out: 9
  swagger_enabled: true
logging:
  projectName: *projectName
  code: logrus
  encoding: console
  level: debug
  dateTimeFormat: 2006-01-02 15:04:05
  dateFormat: 2006-01-02
  enableCaller: false
  devMode: true
http:
  host: 127.0.0.1
  port: 8080
