project:
  name: &projectName Open Budget Core
  version: 1.0.0
  time_out: 9
  swagger_enabled: false
logging:
  projectName: *projectName
  code: zap
  encoding: json
  level: warning
  dateTimeFormat: 2006-01-02 15:04:05
  dateFormat: 2006-01-02
  enableCaller: true
  devMode: false
